OvgBlog.UI/Models/ArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OvgBlog.UI.Models
{
    public class ArticleViewModel
    {
        public string Title { get; set; }
        public string Body { get; set; }
        public string SeoUrl { get; set; }
        public string ImageUrl { get; set; }
    }
}

OvgBlog.UI/Controllers/ArticleController.cs
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OvgBlog.Business.Abstract;
using OvgBlog.UI.Models;
using System.Threading.Tasks;
using System.Linq;
using System.Threading;

namespace OvgBlog.UI.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly IUserService _userService;
        private readonly ITagService _tagService;
        private readonly ILogger<ArticleController> _logger;

        public ArticleController(ILogger<ArticleController> logger, IArticleService articleService, IUserService userService, ITagService tagService)
        {
            _logger = logger;
            _articleService = articleService;
            _userService = userService;
            _tagService = tagService;
        }

        [HttpGet("article/{seoUrl}")]
        public async Task<IActionResult> Index(string seoUrl, CancellationToken cancellationToken)
        
         {
            if (string.IsNullOrEmpty(seoUrl))
            {
                return RedirectToAction("Index", "Home");
            }

            var response = await _articleService.GetBySeoUrlAsync(seoUrl, cancellationToken);           
            if (!response.IsSuccess)
            {
                return RedirectToAction("Index", "Home");
            }
            response.Data.Comments = response.Data.Comments.Where(x => !x.IsDeleted).ToList();
            var articleTags = await _tagService.GetAllAsync(cancellationToken);
            if (articleTags.Data == null || !articleTags.IsSuccess || response.Data.ArticleTagRelations.Count == 0)
            {
                var model = response.Data.Adapt<ArticleDetailViewModel>();               
                var userResponse = await _userService.GetByIdAsync(response.Data.UserId, cancellationToken);
                if (userResponse.IsSuccess)
                {
                    model.UserName = userResponse.Data.Name;
                }               
                return View(model);
            }
            else
            {
                var articleTagIds = response.Data.ArticleTagRelations.Select(x => x.TagId).ToList();
                var tagListResponse = await _tagService.GetByIdsAsync(articleTagIds, cancellationToken);
                
                var model = response.Data.Adapt<ArticleDetailViewModel>();                
                foreach (var item in tagListResponse.Data)
                {
                   if(item.ArticleTagRelations.Where(x => !x.Tag.IsDeleted).Any())
                    {
                        model.Tags.Add(item.Adapt<TagViewModel>());
                    }                   
                }
                var userResponse = await _userService.GetByIdAsync(response.Data.UserId, cancellationToken);
                if (userResponse.IsSuccess)
                {
                    model.UserName = userResponse.Data.Name;
                }
                return View(model);
            }

        }
        
    }
}

OvgBlog.UI/Controllers/CommentController.cs
using Mapster;
using Microsoft.AspNetCore.Mvc;
using OvgBlog.Business.Abstract;
using OvgBlog.DAL.Data;
using OvgBlog.UI.Extentions;
using OvgBlog.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace OvgBlog.UI.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;
        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(CommentAddViewModel commentAddViewModel, CancellationToken cancellationToken)
        {
            if (!ModelState.IsValid || !commentAddViewModel.Email.EmailValidation())
            {
                return Json(new JsonResultModel<CommentAddViewModel>(false, "Model is not valid."));
            }
            var model = commentAddViewModel.Adapt<Comment>();
            var result = await _commentService.CreateAsync(model, cancellationToken);
            if (!result.IsSuccess || result.Data == null)
            {
                return Json(new JsonResultModel<CommentAddViewModel>(false, "Model is not valid."));
            }
            return Json(new JsonResultModel<CommentAddViewModel>(true, "Model is valid."));
        }
    }
}

OvgBlog.UI/Views/Article/Index.cshtml
@model ArticleDetailViewModel
@{
    ViewData["Title"] = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Header -->
<header class="header header-mini">
    <div class="header-title">@Model.Title</div>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Ana Sayfaya Git</a></li>
        </ol>
    </nav>
</header>
<!-- End Of Page Header -->
<body>

    <div class="container">
        <h3 class="mt-5">@Model.Title</h3>
        <p class="blog-card-caption">
            <a href="javascript:;"><i class="fa fa-user-circle-o"></i> Yazar: Admin</a>
            <a href="javascript:;"><i class="fa fa-user-circle-o"></i> Category: Admin</a>
            <a href="javascript:;"><i class="fa fa-calendar-o"></i> Tarih: @Model.CreatedDate.ToString("dd.MM.yyyy")</a>
        </p>
        <img src="~/uploads/@Model.ImageUrl" /><br><br>
        <p>
            @Html.Raw(Model.Body)
        </p><br />
        @foreach (var item in Model.Tags)
        {
            <span class="badge rounded-pill bg-primary text-light">@item.Name</span>
        }
        <!-- testimonial section -->
        <section class="section" id="testmonial">
            <div class="container text-center">
                <h6 class="section-title mb-6">Yorumlar</h6>
                <!-- row -->
                <div class="row">
                    @foreach (var item in Model.Comments)
                    {
                        <div class="col-md-6">
                            <div class="testimonial-card">
                                <div class="testimonial-card-img-holder">
                                    <img src="~/uploads/DefaultCategory.png" class="testimonial-card-img" alt="@item.Name">
                                </div>
                                <div class="testimonial-card-body">
                                    <p class="testimonial-card-subtitle">@item.Body</p>
                                    <h6 class="testimonial-card-title">@item.Name - @item.Email</h6>
                                </div>
                            </div>
                        </div>
                    }

                </div>
            </div>
            <!-- end of container -->
        </section>

        <!-- end of testimonial section -->
        <!-- contact section -->
        <section class="section" id="contact">
            <div class="container text-center">
                <p class="section-subtitle">Yazı hakkında yorum yazmak ister misin?</p>
                <h6 class="section-title mb-5">Yorumunu Yaz</h6>
                <!-- contact form -->
                <form action="" class="contact-form col-md-10 col-lg-8 m-auto">
                    <div class="form-row">
                        <div><input id="@Model.Id" name="@Model.Id" type="hidden"></div>
                        <div class="form-group col-sm-6">
                            <input type="text" size="50" class="form-control" name="Name" id="Name" placeholder="Ad Soyad" required>
                        </div>
                        <div class="form-group col-sm-6">
                            <input type="email" class="form-control" name="Email" id="Email" placeholder="E-posta" requried>
                        </div>
                        <div class="form-group col-sm-12">
                            <textarea name="Body" id="Body" rows="6" class="form-control" placeholder="Bir şeyler yaz"></textarea>
                        </div>
                        <div class="form-group col-sm-12 mt-3">
                            <button type="button" id="sendVal" class="btn btn-outline-primary rounded">Gönder</button>
                        </div>
                    </div>
                </form><!-- end of contact form -->
            </div><!-- end of container -->
        </section>
        <!-- end of contact section -->
    </div>
</body>

@section scripts{
    <script type="text/javascript">
        $('#contact #sendVal').on('click', function () {

         var ArticleId = "@Model.Id"; @*$("#@Model.Id").val()*@
         var name = $("#Name").val();
         var email = $("#Email").val();
         var body = $("#Body").val();
            $.ajax({
                type: 'post',
                url: '@Url.Action("AddComment","Comment")',
                data: { ArticleId, name, email, body },
            success: function (result) {
                if (result.success)
                {
                    location.reload();
                }
                else
                {
                    alert(result.message);
                }
            }
        });
    });


    </script>
}