OvgBlog.UI/Models/HomeViewModel.cs
using System.Collections.Generic;

namespace OvgBlog.UI.Models
{
    public class HomeViewModel
    {
        public List<ArticleListViewModel> Articles { get; set; } = [];
        public List<CategoryListViewModel> Categories { get; set; } = [];
    }
}

OvgBlog.UI/Controllers/ArticleController.cs
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OvgBlog.Business.Abstract;
using OvgBlog.UI.Models;
using System.Threading.Tasks;
using System.Linq;
using System.Threading;

namespace OvgBlog.UI.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly IUserService _userService;
        private readonly ITagService _tagService;
        private readonly ILogger<ArticleController> _logger;

        public ArticleController(ILogger<ArticleController> logger, IArticleService articleService, IUserService userService, ITagService tagService)
        {
            _logger = logger;
            _articleService = articleService;
            _userService = userService;
            _tagService = tagService;
        }

        [HttpGet("article/{seoUrl}")]
        public async Task<IActionResult> Index(string seoUrl, CancellationToken cancellationToken)
        
         {
            if (string.IsNullOrEmpty(seoUrl))
            {
                return RedirectToAction("Index", "Home");
            }

            var response = await _articleService.GetBySeoUrlAsync(seoUrl, cancellationToken);           
            if (!response.IsSuccess)
            {
                return RedirectToAction("Index", "Home");
            }
            response.Data.Comments = response.Data.Comments.Where(x => !x.IsDeleted).ToList();
            var articleTags = await _tagService.GetAllAsync(cancellationToken);
            if (articleTags.Data == null || !articleTags.IsSuccess || response.Data.ArticleTagRelations.Count == 0)
            {
                var model = response.Data.Adapt<ArticleDetailViewModel>();               
                var userResponse = await _userService.GetByIdAsync(response.Data.UserId, cancellationToken);
                if (userResponse.IsSuccess)
                {
                    model.UserName = userResponse.Data.Name;
                }               
                return View(model);
            }
            else
            {
                var articleTagIds = response.Data.ArticleTagRelations.Select(x => x.TagId).ToList();
                var tagListResponse = await _tagService.GetByIdsAsync(articleTagIds, cancellationToken);
                
                var model = response.Data.Adapt<ArticleDetailViewModel>();                
                foreach (var item in tagListResponse.Data)
                {
                   if(item.ArticleTagRelations.Where(x => !x.Tag.IsDeleted).Any())
                    {
                        model.Tags.Add(item.Adapt<TagViewModel>());
                    }                   
                }
                var userResponse = await _userService.GetByIdAsync(response.Data.UserId, cancellationToken);
                if (userResponse.IsSuccess)
                {
                    model.UserName = userResponse.Data.Name;
                }
                return View(model);
            }

        }
        
    }
}

OvgBlog.UI/Controllers/HomeController.cs
using MailKit.Net.Smtp;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MimeKit;
using OvgBlog.Business.Abstract;
using OvgBlog.DAL.Data;
using OvgBlog.UI.Extentions;
using OvgBlog.UI.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace OvgBlog.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly ICategoryService _categoryService;
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _configuration;
        private readonly IContactService _contactService;

        public HomeController(ILogger<HomeController> logger, 
            IArticleService articleService, 
            ICategoryService categoryService,
            IConfiguration configuration,
            IContactService contactService
            )
        {
            _configuration = configuration;
            _logger = logger;
            _articleService = articleService;
            _categoryService = categoryService;
            _contactService = contactService;
        }

        public async Task<IActionResult> Index(CancellationToken cancellationToken)
        {          
            var model = new HomeViewModel();

           

            return View(model);
        }

        public IActionResult Categories(CancellationToken cancellationToken)
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var model = new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier };
            return View(model);
        }
        [HttpGet]
        public IActionResult AboutMe(CancellationToken cancellationToken)
        {

            return View();
        }
        //[HttpPost]
        //public IActionResult SendEmail(SendEmailViewModel sendEmailViewModel)
        //{           
        //    if (ModelState.IsValid)
        //    {
        //        if (!sendEmailViewModel.Email.EmailValidation())
        //        {
        //            return Json(new JsonResultModel<SendEmailViewModel>(false, "Lütfen doğru bir mail adresi giriniz."));
        //        }
        //        var message = new MimeMessage();
        //        message.From.Add(new MailboxAddress(sendEmailViewModel.Name, sendEmailViewModel.Email));
        //        message.To.Add(new MailboxAddress("Orhan", _configuration["GmailReceiverMail"].ToString()));
        //        message.Subject = sendEmailViewModel.Name;
        //        message.Body = new TextPart("plain")
        //        {
        //            Text = "\nEmail:\n" + sendEmailViewModel.Email+ "\nAdı soyadı:\n" + sendEmailViewModel.Name + "\nMesajı:\n" + sendEmailViewModel.Body
        //        };
        //        using (var client = new SmtpClient())
        //        {
        //            client.Connect("smtp.gmail.com", 587, false);                  
        //            client.Authenticate(_configuration["GmailSenderMail"].ToString(), _configuration["GmailSenderPassword"].ToString());
        //            client.Send(message);
        //            client.Disconnect(true);
        //        }
        //        return Json(new JsonResultModel<SendEmailViewModel>(true, "Gönderildi."));
        //    }
        //    else
        //    {
        //        return Json(new JsonResultModel<SendEmailViewModel>(false, "Eksik alanları doldurun."));
        //    }

        //}
        [HttpPost]
        public async Task<IActionResult> AddContact(ContactListViewModel contactListViewModel, CancellationToken cancellationToken)
        {
            if (!ModelState.IsValid)
            {
                return Json(new JsonResultModel<ContactListViewModel>(false, "Alanları doldurun."));
            }
            var model = contactListViewModel.Adapt<Contact>();
            await _contactService.CreateAsync(model, cancellationToken);
            return Json(new JsonResultModel<ContactListViewModel>(true, "Mesajınız iletildi en kısa sürede geri dönüş yapılacaktır."));
        }
    }
}

OvgBlog.UI/Views/Home/AboutMe.cshtml
@{
    ViewData["Title"] = "Hakkımda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section>
    <style>
        .LongText
        {
            width:500px;
            height:350px;
            overflow:hidden;
            text-overflow: ellipsis;
            word-wrap:break-word;
        }
        .linkedin
        {
            font-size:small;
            width:30px;
            height;30px;
        }
        .github {
            font-size: small;
            width: 30px;
            height: 30px;
            position:relative;
            left:10px;
            
        }
        
    </style>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="p-5">
                    <img class="img-fluid rounded-circle" src="~/uploads/Foto.jpg">
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">
                        <a style="color:orangered">HAKKIMDA</a>
                    </h2>
                    <p class="LongText">
                        Merhaba,<br /><br />

                        Ben Orhan, bir oyun şirketinde Game&Level Designer olarak çalışmaktayım. Backend yazılım konusunda ASP.NET CORE,MVC,Entity Frameworkcore, MsSql ve git gibi güncel teknolojiler hakkında eğitim alarak, bu bağlamda bireysel çalışmalar yürütmekteyim. Çalışmalarımı SOLID prensiplerine uygun olarak tasarlamaktayım.<br /><br />

                        Saygılarımla,<br /><br />

                        Orhan Veli GÖĞEBAKAN<br />

                        <br /><a href="https://www.linkedin.com/in/orhan-veli-göğebakan-51a176172"><img src="~/uploads/linkedin.png" class="linkedin" /></a>

                        <a href="https://github.com/Orhan-Veli"><img src="~/uploads/github.png" class="github"></a> <br /><br /><br />

                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

OvgBlog.UI/Views/Home/Index.cshtml
@model HomeViewModel
@{
    ViewData["Title"] = "Ana Sayfa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- page header -->
<header id="home" class="header">
    <div class="overlay"></div>
    <div class="header-content container">
        <h1 class="header-title">
            <span class="up">Merhaba!</span>
            <span class="down">Ben Orhan Veli</span>
        </h1>
        <p class="header-subtitle">BACKEND DEVELOPER</p>

        <a href="https://github.com/Orhan-Veli" target="_blank" class="btn btn-primary">GitHub</a>
    </div>
</header>
<!-- end of page header -->
<!-- about section -->
<section class="section pt-0" id="about">
    <!-- container -->
    <div class="container text-center">
        <!-- about wrapper -->
        <div class="about">
            <div class="about-img-holder">
                <img src="~/uploads/Foto.jpg" class="about-img" alt="" style="border-radius: 50%;">
            </div>
            <div class="about-caption">
                <p class="section-subtitle">Ben Kimim ?</p>
                <h2 class="section-title mb-3">Hakkımda</h2>
                <p class="LongText">
                    Merhaba!<br><br> Ben Orhan, IQ GAMES şirketinde Game&Level Designer olarak çalışmaktayım. Backend yazılım konusunda ASP.NET CORE,MVC,Entity Frameworkcore, MsSql ve git gibi güncel teknolojiler hakkında eğitim alarak, bu bağlamda bireysel çalışmalar yürütmekteyim. Çalışmalarımı SOLID prensiplerine uygun olarak tasarlamaktayım.<br /><br />

                    Saygılarımla,<br /><br />

                    Orhan Veli GÖĞEBAKAN<br />

                </p>
                @*<button class="btn-rounded btn btn-outline-primary mt-4">Download CV</button>*@
            </div>
        </div><!-- end of about wrapper -->
    </div><!-- end of container -->
</section>
<!-- end of about section -->
<!-- service section -->
<section class="section" id="service">
    <div class="container text-center">
        <p class="section-subtitle">Neler Var ?</p>
        <h6 class="section-title mb-6">Kategoriler</h6>
        <!-- row -->
        <div class="row">
            @foreach (var item in Model.Categories)
            {
                <div class="col-md-6 col-lg-3">
                    <div class="service-card">
                        <div class="body">
                            <img src="~/@item.ImageUrl" alt="@item.Name" class="icon">
                            <h6 class="title">@item.Name</h6>
                            <p class="subtitle fa-fw" style="text-align:center !important;">
                                <a href="@Url.Action("Detail", "Category", new { seoUrl = item.SeoUrl })">Yazıları görüntüle</a>
                            </p>
                        </div>
                    </div>
                </div>
            }
        </div><!-- end of row -->
    </div>
</section>
<!-- end of service section -->
<!-- section -->
<section class="section-sm bg-primary">
    <!-- container -->
    <div class="container text-center text-sm-left">
        <!-- row -->
        <div class="row align-items-center">
            <div class="col-sm offset-md-1 mb-4 mb-md-0">
                <h6 class="title text-light">Benimle çalışmak ister misin?</h6>
                <p class="m-0 text-light">Benimle iletişime geçmek için formu doldurabilirsin.</p>
            </div>
            <div class="col-sm offset-sm-2 offset-md-3">
                <a href="#contact" class="btn btn-lg my-font btn-light rounded">Forma Git</a>
            </div>
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</section>
<!-- end of section -->
<!-- blog section -->
<section class="section" id="blog">
    <!-- container -->
    <div class="container text-center">
        @*<p class="section-subtitle">Son Yazılar</p>*@
        <h6 class="section-title mb-6">Son Yazılar</h6>
        @foreach (var item in Model.Articles)
        {
            <!-- blog-wrapper -->
            <div class="blog-card">
                <div class="blog-card-header">
                    <img src="~/uploads/@item.ImageUrl" class="blog-card-img" alt="@item.Title">
                </div>
                <div class="blog-card-body">
                    <h5 class="blog-card-title">@item.Title</h5>

                    <p class="blog-card-caption">
                        <a href="javascript:;"><i class="fa fa-user-circle-o"></i> Yazar: Admin</a>
                        <a href="javascript:;"><i class="fa fa-calendar-o"></i> Tarih: @item.CreatedDate?.ToString("dd.MM.yyyy")</a>
                    </p>

                    <p>@Html.Raw(item.Body)</p>

                    <a asp-controller="Article" asp-action="Index" asp-route-seoUrl="@item.SeoUrl" class="blog-card-link">Devamını oku <i class="ti-angle-double-right"></i></a>
                </div>
            </div>
            <!-- end of blog wrapper -->
        }

    </div><!-- end of container -->
</section>
<!-- end of blog section -->
<!-- contact section -->
<section class="section" id="contact">
    <div class="container text-center">
        <p class="section-subtitle">Benimle nasıl iletişime geçmek istersin?</p>
        <h6 class="section-title mb-5">İletişim Formu</h6>       
        <!-- contact form -->
        <form action="" class="contact-form col-md-10 col-lg-8 m-auto">
            <div class="form-row">
                <div class="form-group col-sm-6">
                    <input type="text" size="50" name="Name" id="Name" class="form-control" placeholder="Ad Soyad" required>
                </div>
                <div class="form-group col-sm-6">
                    <input type="email" name="Email" id="Email" class="form-control" placeholder="E-posta" requried>
                </div>
                <div class="form-group col-sm-12">
                    <textarea name="Body" id="Body" rows="6" class="form-control" placeholder="Bir şeyler yaz" required></textarea>
                </div>
                <div class="form-group col-sm-12 mt-3">
                    <button type="button" id="sendEmail" class="btn btn-outline-primary rounded">Gönder</button>
                </div>
            </div>
        </form><!-- end of contact form -->
    </div><!-- end of container -->
</section>
<!-- end of contact section -->
@section scripts{
    <script>
        $("#sendEmail").on('click', function () {
            var name = $("#Name").val();
            var email = $("#Email").val();
            var body = $("#Body").val();        
            $.ajax({
                type: "post",
                data: { name, email, body },
                url: "@Url.Action("AddContact", "Home")",
                success: function (result) {
                    if (!result.success) {
                       
                        //toastr.error(result.message ?? "Boş alanları doldurunuz.");
                        alert("Boş alanları doldurunuz veya geçerli değerler giriniz.");
                    }
                    else {
                        location.reload();
                        alert(result.message);
                    }
                }
            });
        });
    </script>
}